export {default as Home} from './Home/Home'
export {default as Profile} from './Profile/Profile'
export {default as Explore} from './Explore/Explore'
export {default as News} from './News/News'
export {default as LoginRotes} from '../navigations/LoginRotes'